/** @jsxImportSource @emotion/react */
// The line above is necessary to use the css emotion function. It is part of the solution 4.
import React, { useState } from "react";
import {
  AppBar,
  Box,
  Button,
  IconButton,
  Menu,
  MenuItem,
  Toolbar,
  Typography,
  // Solution 3 - Solution 3 - Using the styled() function
  styled,
} from "@mui/material";
import { NavLink } from "react-router-dom";
import FlagOutlinedIcon from "@mui/icons-material/FlagOutlined";
import MenuIcon from "@mui/icons-material/Menu";
// Solution 4 - css function
// import { css } from "@emotion/react";
// Solution 5 - Plain CSS - custom class
// Solution 7 - Plain CSS - Autogenerated MUI classes
// import "./MainNavigation.css";
// Solution 6 - Module CSS - custom class
// Solution 8 - Module CSS - Autogenerated MUI classes
import classes from "./MainNavigation.module.css";

const navItems = [
  { name: "Home", path: "" },
  { name: "Interactive map", path: "interactive-map" },
  { name: "Statistics", path: "statistics" },
  { name: "About", path: "about" },
];

const MainNavigation = () => {
  const [menuAnchor, setMenuAnchor] = useState(null);

  // console.log("boolean menuAnchor:", Boolean(menuAnchor));

  const openMenuHandler = (event) => {
    // console.log("openMenuHandler");
    // console.log(event);
    // console.log(event.currentTarget);
    setMenuAnchor(event.currentTarget);
  };

  const closeMenuHandler = () => {
    // console.log("closeMenuHandler");
    setMenuAnchor(null);
  };

  // Solution 3 - Using the styled() function
  const DemoNav = styled(AppBar)(() => ({
    backgroundColor: "orange",
  }));

  return (
    <Box sx={{ flexGrow: 1 }}>
      <AppBar
        position="static"
        // Solution 1 - Components props API
        // variant="outlined"
        // color="secondary"
        // Solution 2 - Sx prop
        // sx={{ backgroundColor: "red" }}
        // Solution 4 - css function
        // css={css`
        //   background-color: pink;
        // `}
        // Solution 5 - Plain CSS - custom class
        // className="demo-nav"
        // Solution 6 - Plain CSS - Autogenerated MUI classes
        // Doesn't need to specify a className - CSS is global
        // Solution 7 - Module CSS
        // className={classes["demo-nav"]}
        // Solution 8 - Module CSS - Autogenerated MUI classes
        // Doesn't need to specify a className - CSS is global

        className={classes.header}
      >
        {/* Solution 3 - Solution 3 - Using the styled() function */}
        {/* <DemoNav position="static" variant="outlined"> */}
        <Toolbar component="nav">
          {/* MENU - START */}
          <Box sx={{ display: { sm: "block", md: "none" } }}>
            <IconButton
              size="large"
              aria-label="menu of the website"
              aria-controls="menu-appbar"
              aria-haspopup="true"
              onClick={openMenuHandler}
              color="inherit"
            >
              <MenuIcon />
            </IconButton>
            <Menu
              id="menu-appbar"
              anchorEl={menuAnchor}
              keepMounted
              open={Boolean(menuAnchor)}
              onClose={closeMenuHandler}
              sx={{
                display: { sm: "block", md: "none" },
              }}
            >
              {navItems.map((item) => (
                <MenuItem key={item.name} onClick={closeMenuHandler}>
                  <NavLink
                    to={item.path}
                    className={({ isActive }) => (isActive ? "activate" : "")}
                  >
                    {item.name}
                  </NavLink>
                </MenuItem>
              ))}
            </Menu>
          </Box>
          {/* MENU - END */}
          {/* ICON - START */}
          <Box
            sx={{
              flexGrow: { xs: 1, md: 0 },
              display: { xs: "flex", md: "block" },
              justifyContent: { xs: "center", md: "normal" },
            }}
          >
            <NavLink to="">
              <FlagOutlinedIcon />
            </NavLink>
          </Box>
          {/* ICON -END */}
          {/* TABLET - START */}
          <Box sx={{ display: { xs: "none", md: "block" } }}>
            {navItems.map((item) => (
              <Button key={item.name} sx={{ mx: "20px" }}>
                <NavLink
                  to={item.path}
                  // Solution 1 - with only "active" class dynamically set in css - Research have to be done bc we have a different behavior in the course

                  // Solution 2 - with the custom class "activate" when the link is active
                  // className={({ isActive }) => (isActive ? "activate" : "")}
                >
                  {item.name}
                </NavLink>
              </Button>
            ))}
          </Box>
          {/* TABLET END */}
        </Toolbar>
        {/* </DemoNav> */}
      </AppBar>
    </Box>
  );
};

export default MainNavigation;
