import "./App.css";
import { RouterProvider, createBrowserRouter } from "react-router-dom";
import {
  StyledEngineProvider,
  ThemeProvider,
  createTheme,
} from "@mui/material";
import { blue, deepOrange, yellow } from "@mui/material/colors";
import Root from "./pages/Root";
import Home from "./pages/Home";
import InteractiveMap from "./pages/InteractiveMap";
import Statistics from "./pages/Statistics";
import About from "./pages/About";

const router = createBrowserRouter([
  {
    path: "/",
    element: <Root />,
    children: [
      {
        index: true,
        element: <Home />,
      },
      {
        path: "interactive-map",
        element: <InteractiveMap />,
      },
      {
        path: "statistics",
        element: <Statistics />,
      },
      {
        path: "about",
        element: <About />,
      },
    ],
  },
]);

function App() {
  // Solution 9 - using a theme
  const theme = createTheme({
    // Customize the palette
    palette: {
      primary: deepOrange,
      // secondary: yellow,
      secondary: {
        light: yellow[100],
        main: yellow[500],
        dark: yellow[900],
        contrastText: blue[900],
      },
    },
    // Customize MUI components
    components: {
      // Button MUI component
      MuiButton: {
        defaultProps: {
          disableRipple: true,
          disableElevation: true,
        },
        // The style overriding has the priority on the palette
        // styleOverrides: {
        //   root: {
        //     backgroundColor: "brown",
        //     "&:hover": {
        //       backgroundColor: "lightblue",
        //     },
        //   },
        // },
      },
    },
  });

  return (
    // StyledEngineProvider is needed for:
    // Solution 5 - Plain CSS - custom class
    // Solution 6 - Plain CSS - Autogenerated MUI classes
    // Solution 7 - Module CSS - custom class
    // Solution 8 - Module CSS - Autogenerated MUI classes
    <StyledEngineProvider injectFirst>
      <ThemeProvider theme={theme}>
        <RouterProvider router={router}></RouterProvider>
      </ThemeProvider>
    </StyledEngineProvider>
  );
}

export default App;
